package com.lightquery.support;

import com.lightquery.LightQuery;

import org.h2.jdbcx.JdbcDataSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

/**
 * Test databases outside the standard TestDb schema (v0.2 feature fixtures).
 * Each helper creates an isolated in-memory H2 database and registers it as
 * the facade primary so tests use {@code LightQuery.queryable(...)} directly.
 */
public final class TestSupport {

    private final DataSource dataSource;

    private TestSupport(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public static TestSupport employeeDb(String name) {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1");
        try (Connection connection = ds.getConnection();
             Statement st = connection.createStatement()) {
            st.execute("DROP TABLE IF EXISTS \"t_employee\"");
            st.execute("""
                    CREATE TABLE "t_employee" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" VARCHAR(100),
                        "manager_id" BIGINT,
                        "salary" DECIMAL(12,2),
                        "deleted" INT DEFAULT 0
                    )""");
        } catch (SQLException e) {
            throw new IllegalStateException("cannot prepare H2 schema", e);
        }
        LightQuery.reset();
        LightQuery.primary(ds);
        return new TestSupport(ds);
    }

    public DataSource dataSource() {
        return dataSource;
    }
}
