package com.lightquery.support;

import com.lightquery.LightQuery;
import com.lightquery.LightQuerySession;
import com.lightquery.entity.Order;
import com.lightquery.entity.User;

import org.h2.jdbcx.JdbcDataSource;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;

import javax.sql.DataSource;

/**
 * In-memory H2 database with a fixed schema plus a ready {@link LightQuerySession}
 * instance. Each test class creates its own database name so they stay
 * isolated.
 */
public final class TestDb {

    public final DataSource dataSource;
    public final LightQuerySession db;

    public TestDb(String name) {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1");
        this.dataSource = ds;
        this.db = LightQuery.of(ds);
        try (Connection connection = ds.getConnection();
             Statement st = connection.createStatement()) {
            st.execute("DROP TABLE IF EXISTS \"t_user\"");
            st.execute("""
                    CREATE TABLE "t_user" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "user_name" VARCHAR(100),
                        "status" VARCHAR(20),
                        "age" INT,
                        "balance" DECIMAL(12,2),
                        "created_at" TIMESTAMP,
                        "remark" VARCHAR(200),
                        "deleted" INT DEFAULT 0
                    )""");
            st.execute("DROP TABLE IF EXISTS \"t_user_202401\"");
            st.execute("""
                    CREATE TABLE "t_user_202401" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "user_name" VARCHAR(100),
                        "status" VARCHAR(20),
                        "age" INT,
                        "balance" DECIMAL(12,2),
                        "created_at" TIMESTAMP,
                        "remark" VARCHAR(200),
                        "deleted" INT DEFAULT 0
                    )""");
            st.execute("DROP TABLE IF EXISTS \"t_order\"");
            st.execute("""
                    CREATE TABLE "t_order" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "user_id" BIGINT,
                        "amount" DECIMAL(12,2),
                        "status" INT,
                        "created_at" TIMESTAMP
                    )""");
        } catch (SQLException e) {
            throw new IllegalStateException("cannot prepare H2 schema", e);
        }
    }

    public User user(String name, User.Status status, Integer age, String balance,
                     String remark, int deleted) {
        return new User(name, status, age, balance, LocalDateTime.of(2024, 1, 1, 10, 0),
                remark, deleted);
    }

    public Order order(Long userId, String amount, int status) {
        return new Order(userId, amount, status, LocalDateTime.of(2024, 2, 1, 9, 0));
    }

    public static BigDecimal decimal(String value) {
        return new BigDecimal(value);
    }
}
