package com.lightquery.meta;

import com.lightquery.ValueConverter;
import com.lightquery.exception.MappingException;
import jakarta.persistence.AttributeConverter;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.util.Arrays;
import java.math.BigInteger;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Date;

/**
 * Mapping information of one entity field: its column name, primary-key /
 * insert / update flags, the key generation strategy, the optimistic-lock
 * flag and the enum storage strategy. Also owns the entity&nbsp;↔&nbsp;database
 * value conversions for this column.
 */
public final class ColumnMeta {

    /** How enum values are persisted; mirrors {@link jakarta.persistence.EnumType}. */
    public enum EnumKind { NONE, STRING, ORDINAL }

    /** How the primary key is populated on insert. */
    public enum KeyGeneration { NONE, IDENTITY, SEQUENCE }

    private final Field field;
    private final String propertyName;
    private final String columnName;
    private final boolean primaryKey;
    private final KeyGeneration keyGeneration;
    private final String sequenceName;
    private final boolean version;
    private final boolean insertable;
    private final boolean updatable;
    private final EnumKind enumKind;
    private final boolean logicDelete;
    private final int logicDeleteNormalValue;
    private final int logicDeleteDeletedValue;
    private final AttributeConverter<Object, Object> converter;

    ColumnMeta(Field field, String columnName, boolean primaryKey, KeyGeneration keyGeneration,
               String sequenceName, boolean version, boolean insertable, boolean updatable,
               EnumKind enumKind, boolean logicDelete, int logicDeleteNormalValue,
               int logicDeleteDeletedValue, AttributeConverter<Object, Object> converter) {
        this.field = field;
        this.propertyName = field.getName();
        this.columnName = columnName;
        this.primaryKey = primaryKey;
        this.keyGeneration = keyGeneration;
        this.sequenceName = sequenceName;
        this.version = version;
        this.insertable = insertable;
        this.updatable = updatable;
        this.enumKind = enumKind;
        this.logicDelete = logicDelete;
        this.logicDeleteNormalValue = logicDeleteNormalValue;
        this.logicDeleteDeletedValue = logicDeleteDeletedValue;
        this.converter = converter;
        try {
            this.field.setAccessible(true);
        } catch (RuntimeException e) {
            throw new MappingException("Cannot access field '" + propertyName + "' of "
                    + field.getDeclaringClass().getName() + " — open its module/package to "
                    + "light-query (e.g. --add-opens) or make the field public", e);
        }
    }

    public Field getField() {
        return field;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public String getColumnName() {
        return columnName;
    }

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public boolean isAutoGenerated() {
        return keyGeneration != KeyGeneration.NONE;
    }

    /** True when the key is populated by an IDENTITY column (JDBC generated keys). */
    public boolean isIdentity() {
        return keyGeneration == KeyGeneration.IDENTITY;
    }

    /** True when the key is populated from a database sequence before the INSERT. */
    public boolean isSequence() {
        return keyGeneration == KeyGeneration.SEQUENCE;
    }

    /** The sequence name for a SEQUENCE key, null otherwise. */
    public String getSequenceName() {
        return sequenceName;
    }

    /** True when the field carries {@code @Version} (optimistic lock). */
    public boolean isVersion() {
        return version;
    }

    public boolean isInsertable() {
        return insertable;
    }

    public boolean isUpdatable() {
        return updatable;
    }

    public boolean isLogicDelete() {
        return logicDelete;
    }

    public int getLogicDeleteNormalValue() {
        return logicDeleteNormalValue;
    }

    public int getLogicDeleteDeletedValue() {
        return logicDeleteDeletedValue;
    }

    /** The "not deleted" marker bound to JDBC (Boolean for boolean columns). */
    public Object normalValueAsDb() {
        return asLogicDbValue(logicDeleteNormalValue);
    }

    /** The "deleted" marker bound to JDBC (Boolean for boolean columns). */
    public Object deletedValueAsDb() {
        return asLogicDbValue(logicDeleteDeletedValue);
    }

    private Object asLogicDbValue(int value) {
        Class<?> type = field.getType();
        if (type == boolean.class || type == Boolean.class) {
            return value != 0;
        }
        return value;
    }

    EnumKind getEnumKind() {
        return enumKind;
    }

    // ------------------------------------------------------------------ values

    /** Reads the property value from an entity instance. */
    public Object readValue(Object entity) {
        try {
            return field.get(entity);
        } catch (IllegalAccessException e) {
            throw new MappingException("Cannot read property '" + propertyName
                    + "' of " + field.getDeclaringClass().getName(), e);
        }
    }

    /** Writes a database value into an entity instance, coercing numbers when needed. */
    public void writeValue(Object entity, Object value) {
        try {
            if (value == null) {
                if (!field.getType().isPrimitive()) {
                    field.set(entity, null);
                }
                // primitive stays at its default; documented in DESIGN §4.3
                return;
            }
            field.set(entity, coerce(value));
        } catch (IllegalAccessException e) {
            throw new MappingException("Cannot write property '" + propertyName
                    + "' of " + field.getDeclaringClass().getName(), e);
        }
    }

    /** Converts an entity property value into the value bound to JDBC. */
    public Object toDbValue(Object value) {
        if (value != null) {
            if (converter != null) {
                value = convertByFieldConverterToDb(value);
            } else if (enumKind == EnumKind.NONE) {
                // enum fields convert through the enum storage kind; a global
                // converter output would not be an enum and would break the cast
                ValueConverter<Object, Object> global = Converters.forType(field.getType());
                if (global != null) {
                    value = convertByGlobalToDb(global, value);
                }
            }
        }
        if (value == null || enumKind == EnumKind.NONE) {
            return value;
        }
        Enum<?> e = (Enum<?>) value;
        return enumKind == EnumKind.STRING ? e.name() : e.ordinal();
    }

    /** Converts a raw JDBC value into the property type. */
    public Object fromDbValue(Object value) {
        if (converter != null) {
            return converter.convertToEntityAttribute(value);
        }
        if (value != null && enumKind == EnumKind.NONE) {
            ValueConverter<Object, Object> global = Converters.forType(field.getType());
            if (global != null) {
                return global.fromDatabase(value);
            }
        }
        if (value == null || enumKind == EnumKind.NONE) {
            return value;
        }
        return enumKind == EnumKind.STRING
                ? enumFromName(value.toString())
                : enumFromOrdinal(((Number) value).intValue());
    }

    private Object convertByFieldConverterToDb(Object value) {
        try {
            return converter.convertToDatabaseColumn(value);
        } catch (RuntimeException e) {
            throw new MappingException("Converter " + converter.getClass().getSimpleName()
                    + " failed for column '" + columnName + "' (property '" + propertyName
                    + "') on value " + value, e);
        }
    }

    private Object convertByGlobalToDb(ValueConverter<Object, Object> global, Object value) {
        try {
            return global.toDatabase(value);
        } catch (RuntimeException e) {
            throw new MappingException("ValueConverter " + global.getClass().getSimpleName()
                    + " failed for column '" + columnName + "' (property '" + propertyName
                    + "') on value " + value, e);
        }
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private Object enumFromName(String name) {
        try {
            return Enum.valueOf((Class<? extends Enum>) field.getType(), name);
        } catch (IllegalArgumentException e) {
            throw new MappingException("Cannot map database value '" + name + "' to enum "
                    + field.getType().getName() + " for column '" + columnName + "' — valid "
                    + "constants: " + Arrays.toString(field.getType().getEnumConstants()), e);
        }
    }

    @SuppressWarnings("unchecked")
    private Object enumFromOrdinal(int ordinal) {
        Class<? extends Enum<?>> type = (Class<? extends Enum<?>>) field.getType();
        Object[] constants = type.getEnumConstants();
        if (ordinal < 0 || ordinal >= constants.length) {
            throw new MappingException("Cannot map database value " + ordinal + " to enum "
                    + type.getName() + " for column '" + columnName + "' — ordinal out of "
                    + "range 0.." + (constants.length - 1) + " (did the enum change order?)");
        }
        return constants[ordinal];
    }

    private Object coerce(Object value) {
        Class<?> type = field.getType();
        if (type.isInstance(value)) {
            return value;
        }
        if (value instanceof Number n) {
            return coerceNumber(n, type);
        }
        if (value instanceof java.sql.Timestamp ts) {
            Object converted = coerceTimestamp(ts, type);
            if (converted != null) {
                return converted;
            }
        }
        if (value instanceof java.sql.Date d && type == LocalDate.class) {
            return d.toLocalDate();
        }
        if (value instanceof java.sql.Time t && type == LocalTime.class) {
            return t.toLocalTime();
        }
        throw new MappingException("Column '" + columnName + "': cannot map value of type "
                + value.getClass().getName() + " to property '" + propertyName + "' of type "
                + type.getName());
    }

    private Object coerceTimestamp(java.sql.Timestamp ts, Class<?> type) {
        if (type == LocalDateTime.class) {
            return ts.toLocalDateTime();
        }
        if (type == Date.class) {
            return new Date(ts.getTime());
        }
        if (type == Instant.class) {
            return ts.toInstant();
        }
        if (type == OffsetDateTime.class) {
            return ts.toInstant().atOffset(ZoneOffset.UTC);
        }
        if (type == LocalDate.class) {
            return ts.toLocalDateTime().toLocalDate();
        }
        if (type == LocalTime.class) {
            return ts.toLocalDateTime().toLocalTime();
        }
        return null;
    }

    private Object coerceNumber(Number n, Class<?> type) {
        if (type == Integer.class || type == int.class) {
            return n.intValue();
        }
        if (type == Long.class || type == long.class) {
            return n.longValue();
        }
        if (type == Short.class || type == short.class) {
            return n.shortValue();
        }
        if (type == Byte.class || type == byte.class) {
            return n.byteValue();
        }
        if (type == Double.class || type == double.class) {
            return n.doubleValue();
        }
        if (type == Float.class || type == float.class) {
            return n.floatValue();
        }
        if (type == BigDecimal.class) {
            return n instanceof BigDecimal bd ? bd : BigDecimal.valueOf(n.doubleValue());
        }
        if (type == BigInteger.class) {
            return n instanceof BigInteger bi ? bi : BigInteger.valueOf(n.longValue());
        }
        return n;
    }
}
