package com.lightquery.exec;

import com.lightquery.exception.MappingException;
import com.lightquery.exception.UnexpectedRowsException;
import com.lightquery.meta.ColumnMeta;
import com.lightquery.meta.EntityMeta;
import com.lightquery.meta.EntityMetaCache;
import com.lightquery.query.model.ColumnRef;
import com.lightquery.query.model.Condition;
import com.lightquery.query.model.Op;
import com.lightquery.query.model.QueryModel;
import com.lightquery.sqlgen.SqlBuilder;
import com.lightquery.sqlgen.SqlFragment;
import com.lightquery.sqlgen.Dialect;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Single-table entity CRUD (insert / update by id / delete by id). Builds
 * SQL through {@link SqlBuilder} and enforces the row-count contracts of the
 * DESIGN (affected rows ≠ 1 → {@link UnexpectedRowsException}).
 */
public final class EntityOperations {

    private EntityOperations() {
    }

    /** Inserts one entity and back-fills an identity primary key if present. */
    public static <E> E insert(ConnectionProvider connections, Dialect dialect, E entity) {
        EntityMeta meta = EntityMetaCache.of(entity.getClass());
        List<ColumnMeta> columns = meta.getInsertableColumns();
        List<String> names = columns.stream().map(ColumnMeta::getColumnName).toList();
        List<Object> values = columns.stream()
                .map(c -> c.toDbValue(c.readValue(entity)))
                .toList();
        SqlFragment fragment = SqlBuilder.insert(meta.getTableName(), names, values, dialect);
        JdbcExecutor.insert(connections, fragment, entity, autoGeneratedKey(meta));
        return entity;
    }

    /** Inserts many entities as one JDBC batch; identity keys are not back-filled. */
    public static <E> List<E> insertBatch(ConnectionProvider connections, Dialect dialect,
                                          Collection<E> entities) {
        if (entities.isEmpty()) {
            return List.of();
        }
        EntityMeta meta = EntityMetaCache.of(entities.iterator().next().getClass());
        List<ColumnMeta> columns = meta.getInsertableColumns();
        List<String> names = columns.stream().map(ColumnMeta::getColumnName).toList();
        List<List<Object>> rows = new ArrayList<>(entities.size());
        for (E entity : entities) {
            rows.add(columns.stream()
                    .map(c -> c.toDbValue(c.readValue(entity)))
                    .toList());
        }
        SqlFragment fragment = SqlBuilder.insert(meta.getTableName(), names, List.of(), dialect);
        JdbcExecutor.insertBatch(connections, fragment, rows);
        return List.copyOf(entities);
    }

    /** Full update by primary key (null columns are written as NULL). */
    public static <E> void update(ConnectionProvider connections, Dialect dialect, E entity) {
        updateEntity(connections, dialect, entity, false);
    }

    /** Update by primary key, writing only non-null properties. */
    public static <E> void updateSelective(ConnectionProvider connections, Dialect dialect, E entity) {
        updateEntity(connections, dialect, entity, true);
    }

    /** Deletes by primary key; becomes a logic-delete UPDATE when mapped. */
    public static <E> void delete(ConnectionProvider connections, Dialect dialect, E entity) {
        EntityMeta meta = EntityMetaCache.of(entity.getClass());
        QueryModel model = new QueryModel(entity.getClass());
        addPkConditions(model, meta, pkValues(meta, entity));
        int rows = executeDelete(connections, dialect, model, meta);
        requireOneRow(rows, "delete", describePk(meta, pkValues(meta, entity)));
    }

    /**
     * Deletes by primary key values; becomes a logic-delete UPDATE when mapped.
     *
     * @return affected rows (0 when the row does not exist — idempotent)
     */
    public static int deleteById(ConnectionProvider connections, Dialect dialect,
                                 Class<?> entityType, Object... pkValues) {
        EntityMeta meta = EntityMetaCache.of(entityType);
        QueryModel model = new QueryModel(entityType);
        addPkConditions(model, meta, validatedPkValues(meta, pkValues));
        return executeDelete(connections, dialect, model, meta);
    }

    /** Selects one entity by primary key values (logic-delete filter applies). */
    public static <E> E queryById(ConnectionProvider connections, Dialect dialect,
                                  Class<E> entityType, Object... pkValues) {
        EntityMeta meta = EntityMetaCache.of(entityType);
        QueryModel model = new QueryModel(entityType);
        addPkConditions(model, meta, validatedPkValues(meta, pkValues));
        addLogicFilter(model, meta);
        SqlFragment fragment = SqlBuilder.select(model, dialect);
        List<E> rows = JdbcExecutor.query(connections, fragment, JdbcExecutor.entityMapper(meta));
        return rows.isEmpty() ? null : rows.get(0);
    }

    /** Counts all rows of a table (logic-delete filter applies). */
    public static long count(ConnectionProvider connections, Dialect dialect, Class<?> entityType) {
        EntityMeta meta = EntityMetaCache.of(entityType);
        QueryModel model = new QueryModel(entityType);
        addLogicFilter(model, meta);
        return JdbcExecutor.count(connections, SqlBuilder.count(model, dialect));
    }

    // ------------------------------------------------------------------ internals

    private static void updateEntity(ConnectionProvider connections, Dialect dialect,
                                     Object entity, boolean selective) {
        EntityMeta meta = EntityMetaCache.of(entity.getClass());
        List<Object> pks = pkValues(meta, entity);
        List<ColumnMeta> setColumns = meta.getUpdatableColumns().stream()
                .filter(c -> !selective || c.readValue(entity) != null)
                .toList();
        if (setColumns.isEmpty()) {
            throw new MappingException("Nothing to update for " + meta.getEntityClass().getName()
                    + (selective ? " — every updatable property is null" : ""));
        }
        QueryModel model = new QueryModel(entity.getClass());
        addPkConditions(model, meta, pks);
        // protect logically deleted rows from being modified
        addLogicFilter(model, meta);

        List<SqlBuilder.SetClause> sets = setColumns.stream()
                .map(c -> SqlBuilder.SetClause.of(c.getColumnName(), c.toDbValue(c.readValue(entity))))
                .toList();
        int rows = JdbcExecutor.execute(connections, SqlBuilder.update(model, sets, dialect));
        requireOneRow(rows, "update", describePk(meta, pks));
    }

    private static int executeDelete(ConnectionProvider connections, Dialect dialect,
                                     QueryModel model, EntityMeta meta) {
        ColumnMeta logic = meta.getLogicDeleteColumn();
        if (logic != null) {
            // already-deleted rows stay deleted: no logic filter on this UPDATE
            SqlBuilder.SetClause mark = SqlBuilder.SetClause.of(
                    logic.getColumnName(), logic.deletedValueAsDb());
            return JdbcExecutor.execute(connections, SqlBuilder.update(model, List.of(mark), dialect));
        }
        return JdbcExecutor.execute(connections, SqlBuilder.delete(model, dialect));
    }

    private static void addPkConditions(QueryModel model, EntityMeta meta, List<Object> pkValues) {
        List<ColumnMeta> pks = meta.getPrimaryKeys();
        for (int i = 0; i < pks.size(); i++) {
            model.getWhere().add(Condition.of(
                    new ColumnRef(meta.getEntityClass(), pks.get(i).getColumnName()),
                    Op.EQ, List.of(pkValues.get(i))));
        }
    }

    private static void addLogicFilter(QueryModel model, EntityMeta meta) {
        ColumnMeta logic = meta.getLogicDeleteColumn();
        if (logic != null) {
            model.getWhere().add(Condition.of(
                    new ColumnRef(meta.getEntityClass(), logic.getColumnName()),
                    Op.EQ, List.of(logic.normalValueAsDb())));
        }
    }

    private static List<Object> pkValues(EntityMeta meta, Object entity) {
        return meta.getPrimaryKeys().stream()
                .map(pk -> pk.readValue(entity))
                .toList();
    }

    private static List<Object> validatedPkValues(EntityMeta meta, Object... pkValues) {
        int expected = meta.getPrimaryKeys().size();
        int actual = pkValues == null ? 0 : pkValues.length;
        if (actual != expected) {
            throw new MappingException(meta.getEntityClass().getSimpleName()
                    + " has " + expected + " primary key column(s) but " + actual
                    + " value(s) were passed");
        }
        return List.of(pkValues);
    }

    private static ColumnMeta autoGeneratedKey(EntityMeta meta) {
        return meta.getPrimaryKeys().stream()
                .filter(ColumnMeta::isAutoGenerated)
                .findFirst()
                .orElse(null);
    }

    private static void requireOneRow(int affected, String operation, String pkDescription) {
        if (affected != 1) {
            throw new UnexpectedRowsException(operation + " by id " + pkDescription
                    + " affected " + affected + " rows (expected 1) — the row may have been "
                    + "deleted concurrently or the primary key may be stale", affected);
        }
    }

    private static String describePk(EntityMeta meta, List<Object> values) {
        List<String> names = meta.getPrimaryKeys().stream()
                .map(ColumnMeta::getColumnName).toList();
        return names + "=" + values;
    }
}
