package com.lightquery.spring;

import com.lightquery.LightQuery;
import com.lightquery.LightQuerySession;
import com.lightquery.exception.LightQueryException;
import com.lightquery.exec.ConnectionProvider;
import com.lightquery.exec.DataSourceConnectionProvider;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;

import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/** T16 — starter auto-configuration and Spring-managed transactions. */
class SpringStarterTest {

    private static JdbcDataSource dataSource;
    private static LightQuerySession plainSession;

    @BeforeAll
    static void setUp() {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:starter;DB_CLOSE_DELAY=-1");
        try (Connection connection = dataSource.getConnection();
             Statement st = connection.createStatement()) {
            st.execute("DROP TABLE IF EXISTS \"t_starter_user\"");
            st.execute("""
                    CREATE TABLE "t_starter_user" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" VARCHAR(100),
                        "deleted" INT DEFAULT 0
                    )""");
        } catch (Exception e) {
            throw new IllegalStateException("cannot prepare H2 schema", e);
        }
        plainSession = new LightQuerySession(
                new DataSourceConnectionProvider(dataSource), LightQuerySession.detectDialect(dataSource));
        LightQuery.reset();
    }

    @BeforeEach
    void clearRegistry() {
        LightQuery.reset();
    }

    @AfterAll
    static void tearDown() {
        LightQuery.reset();
    }

    private static ApplicationContextRunner runner() {
        return new ApplicationContextRunner()
                .withBean(DataSource.class, () -> dataSource)
                .withConfiguration(AutoConfigurations.of(LightQueryAutoConfiguration.class));
    }

    @Test
    void autoConfigurationRegistersSessionAndFacade() {
        runner().run(context -> {
            assertThat(context).hasSingleBean(LightQuerySession.class);
            // the session bean participates: register + query through the facade
            LightQuery.insert(new StarterUser("facade-user"));
            long count = LightQuery.queryable(StarterUser.class)
                    .eq(StarterUser::getName, "facade-user").count();
            assertThat(count).isEqualTo(1);
        });
    }

    @Test
    void userDefinedSessionBeanSkipsAutoConfiguration() {
        new ApplicationContextRunner()
                .withBean(DataSource.class, () -> dataSource)
                .withBean(LightQuerySession.class,
                        () -> new LightQuerySession(new DataSourceConnectionProvider(dataSource),
                                LightQuerySession.detectDialect(dataSource)))
                .withConfiguration(AutoConfigurations.of(LightQueryAutoConfiguration.class))
                .run(context -> {
                    assertThat(context).hasSingleBean(LightQuerySession.class);
                    // the facade was never registered in this scenario
                    org.junit.jupiter.api.Assertions.assertThrows(LightQueryException.class,
                            () -> LightQuery.queryable(StarterUser.class));
                });
    }

    @Test
    void withoutDataSourceNothingIsConfigured() {
        new ApplicationContextRunner()
                .withConfiguration(AutoConfigurations.of(LightQueryAutoConfiguration.class))
                .run(context -> assertThat(context).doesNotHaveBean(LightQuerySession.class));
    }

    @Test
    void statementsJoinSpringTransactions() {
        ConnectionProvider springProvider = new SpringConnectionProvider(dataSource);
        LightQuerySession session = new LightQuerySession(
                springProvider, LightQuerySession.detectDialect(dataSource));
        TransactionTemplate template = new TransactionTemplate(
                new DataSourceTransactionManager(dataSource));

        // committed transaction: the row survives, and the session did not commit itself
        template.execute(status -> {
            session.insert(new StarterUser("tx-commit"));
            // the same bound connection sees its own uncommitted write
            assertThat(session.queryable(StarterUser.class)
                    .eq(StarterUser::getName, "tx-commit").count()).isEqualTo(1);
            return null;
        });
        assertThat(plainSession.queryable(StarterUser.class)
                .eq(StarterUser::getName, "tx-commit").count()).isEqualTo(1);

        // rolled-back transaction: the row disappears without any light-query rollback
        template.execute(status -> {
            session.insert(new StarterUser("tx-rollback"));
            status.setRollbackOnly();
            return null;
        });
        assertThat(plainSession.queryable(StarterUser.class)
                .eq(StarterUser::getName, "tx-rollback").count()).isEqualTo(0);
    }

    @Test
    void withoutSpringTransactionConnectionsComeFromThePool() {
        ConnectionProvider springProvider = new SpringConnectionProvider(dataSource);
        LightQuerySession session = new LightQuerySession(
                springProvider, LightQuerySession.detectDialect(dataSource));
        org.junit.jupiter.api.Assertions.assertFalse(springProvider.inManagedTransaction());
        session.insert(new StarterUser("no-tx"));
        assertThat(plainSession.queryable(StarterUser.class)
                .eq(StarterUser::getName, "no-tx").count()).isEqualTo(1);
    }
}
