package com.lightquery.meta;

import com.lightquery.annotation.LogicDelete;
import com.lightquery.exception.MappingException;

import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Immutable mapping metadata of one entity class. Built once per class and
 * cached by {@link EntityMetaCache}; every lookup afterwards is a map read.
 */
public final class EntityMeta {

    private final Class<?> entityClass;
    private final String tableName;
    private final Constructor<?> noArgConstructor;
    private final List<ColumnMeta> columns;
    private final Map<String, ColumnMeta> byProperty;
    private final Map<String, ColumnMeta> byColumn;
    private final List<ColumnMeta> primaryKeys;
    private final ColumnMeta logicDeleteColumn;

    EntityMeta(Class<?> entityClass) {
        this.entityClass = entityClass;
        this.tableName = resolveTableName(entityClass);
        this.noArgConstructor = resolveNoArgConstructor(entityClass);

        List<ColumnMeta> parsed = new ArrayList<>();
        Class<?> current = entityClass;
        while (current != null && current != Object.class) {
            for (Field field : current.getDeclaredFields()) {
                if (Modifier.isStatic(field.getModifiers()) || field.isSynthetic()
                        || field.isAnnotationPresent(Transient.class)) {
                    continue;
                }
                parsed.add(parseColumn(entityClass, field));
            }
            current = current.getSuperclass();
        }

        Map<String, ColumnMeta> propMap = new LinkedHashMap<>();
        Map<String, ColumnMeta> colMap = new LinkedHashMap<>();
        List<ColumnMeta> pks = new ArrayList<>();
        ColumnMeta logic = null;
        for (ColumnMeta meta : parsed) {
            if (propMap.put(meta.getPropertyName(), meta) != null) {
                throw new MappingException("Duplicate property name '" + meta.getPropertyName()
                        + "' in " + entityClass.getName());
            }
            if (colMap.put(meta.getColumnName().toLowerCase(), meta) != null) {
                throw new MappingException("Two properties of " + entityClass.getName()
                        + " map to the same column '" + meta.getColumnName() + "'");
            }
            if (meta.isPrimaryKey()) {
                pks.add(meta);
            }
            if (meta.isLogicDelete()) {
                if (logic != null) {
                    throw new MappingException(entityClass.getName()
                            + " declares more than one @LogicDelete field");
                }
                logic = meta;
            }
        }
        if (pks.isEmpty()) {
            throw new MappingException(entityClass.getName()
                    + " has no primary key. Annotate the key field with @Id.");
        }
        if (pks.stream().filter(ColumnMeta::isAutoGenerated).count() > 1) {
            throw new MappingException(entityClass.getName()
                    + " declares more than one @GeneratedValue key — a table can have at most one identity column");
        }
        this.columns = List.copyOf(parsed);
        this.byProperty = Collections.unmodifiableMap(propMap);
        this.byColumn = Collections.unmodifiableMap(colMap);
        this.primaryKeys = List.copyOf(pks);
        this.logicDeleteColumn = logic;
    }

    private static ColumnMeta parseColumn(Class<?> entityClass, Field field) {
        String columnName;
        boolean insertable = true;
        boolean updatable = true;
        Column column = field.getAnnotation(Column.class);
        if (column != null && !column.name().isEmpty()) {
            columnName = column.name();
            insertable = column.insertable();
            updatable = column.updatable();
        } else {
            columnName = camelToSnake(field.getName());
        }

        Id id = field.getAnnotation(Id.class);
        boolean primaryKey = id != null;
        boolean autoGenerated = false;
        if (primaryKey) {
            GeneratedValue generated = field.getAnnotation(GeneratedValue.class);
            if (generated != null) {
                if (generated.strategy() != GenerationType.IDENTITY) {
                    throw new MappingException(entityClass.getName() + "." + field.getName()
                            + ": only GenerationType.IDENTITY is supported (SEQUENCE arrives in v0.2)");
                }
                autoGenerated = true;
            }
        }

        ColumnMeta.EnumKind enumKind = ColumnMeta.EnumKind.NONE;
        if (field.getType().isEnum()) {
            Enumerated enumerated = field.getAnnotation(Enumerated.class);
            // JPA default is ORDINAL — highlighted in the README on purpose
            enumKind = enumerated != null && enumerated.value() == EnumType.STRING
                    ? ColumnMeta.EnumKind.STRING
                    : ColumnMeta.EnumKind.ORDINAL;
        }

        LogicDelete logicDelete = field.getAnnotation(LogicDelete.class);
        return new ColumnMeta(field, columnName, primaryKey, autoGenerated, insertable, updatable,
                enumKind, logicDelete != null,
                logicDelete != null ? logicDelete.normalValue() : 0,
                logicDelete != null ? logicDelete.deletedValue() : 1);
    }

    // ------------------------------------------------------------------ lookups

    public Class<?> getEntityClass() {
        return entityClass;
    }

    public String getTableName() {
        return tableName;
    }

    public List<ColumnMeta> getColumns() {
        return columns;
    }

    /** Columns present in INSERT statements (excludes identity keys and insertable=false). */
    public List<ColumnMeta> getInsertableColumns() {
        return columns.stream()
                .filter(c -> c.isInsertable() && !(c.isPrimaryKey() && c.isAutoGenerated()))
                .toList();
    }

    /** Columns present in full UPDATE statements (excludes keys and updatable=false). */
    public List<ColumnMeta> getUpdatableColumns() {
        return columns.stream()
                .filter(c -> !c.isPrimaryKey() && c.isUpdatable())
                .toList();
    }

    public List<ColumnMeta> getPrimaryKeys() {
        return primaryKeys;
    }

    /** The {@code @LogicDelete} column, or null when the entity has none. */
    public ColumnMeta getLogicDeleteColumn() {
        return logicDeleteColumn;
    }

    public ColumnMeta byProperty(String propertyName) {
        return byProperty.get(propertyName);
    }

    public ColumnMeta byColumn(String columnName) {
        return byColumn.get(columnName.toLowerCase());
    }

    /**
     * Finds the mapped column for a result-set label: exact column name,
     * case-insensitive, then snake_case label → camelCase property.
     */
    public ColumnMeta byLabel(String label) {
        ColumnMeta meta = byColumn.get(label.toLowerCase());
        if (meta != null) {
            return meta;
        }
        if (label.indexOf('_') >= 0) {
            return byProperty.get(camelCase(label));
        }
        return null;
    }

    /** Creates a fresh entity instance via its no-arg constructor. */
    @SuppressWarnings("unchecked")
    public <E> E newEntity() {
        try {
            return (E) noArgConstructor.newInstance();
        } catch (ReflectiveOperationException e) {
            throw new MappingException("Cannot instantiate " + entityClass.getName()
                    + " — it must expose a public no-arg constructor", e);
        }
    }

    // ------------------------------------------------------------------ naming

    private static String resolveTableName(Class<?> entityClass) {
        Table table = entityClass.getAnnotation(Table.class);
        if (table != null && !table.name().isEmpty()) {
            return table.name();
        }
        return camelToSnake(entityClass.getSimpleName());
    }

    private static Constructor<?> resolveNoArgConstructor(Class<?> entityClass) {
        try {
            Constructor<?> constructor = entityClass.getDeclaredConstructor();
            constructor.setAccessible(true);
            return constructor;
        } catch (NoSuchMethodException e) {
            throw new MappingException(entityClass.getName()
                    + " needs a no-arg constructor to be used as an entity", e);
        }
    }

    /** {@code userName} → {@code user_name}; consecutive capitals collapse into one word. */
    public static String camelToSnake(String name) {
        StringBuilder sb = new StringBuilder(name.length() + 4);
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            boolean boundary = Character.isUpperCase(c)
                    && (i == 0 || !Character.isUpperCase(name.charAt(i - 1)));
            if (boundary && i > 0) {
                sb.append('_');
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }

    private static String camelCase(String snake) {
        StringBuilder sb = new StringBuilder(snake.length());
        boolean upperNext = false;
        for (int i = 0; i < snake.length(); i++) {
            char c = snake.charAt(i);
            if (c == '_') {
                upperNext = true;
            } else {
                sb.append(upperNext ? Character.toUpperCase(c) : c);
                upperNext = false;
            }
        }
        return sb.toString();
    }
}
