package com.lightquery;

import com.lightquery.entity.Wallet;
import com.lightquery.exception.MappingException;
import com.lightquery.support.TestDb;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

/** T29 — global {@link ValueConverter} registry: round-trip, precedence, null pass-through, failures. */
@TestInstance(org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS)
class ConverterRegistryH2Test {

    private static final java.util.concurrent.atomic.AtomicInteger DB_SEQ =
            new java.util.concurrent.atomic.AtomicInteger();

    private TestDb h2;

    @BeforeEach
    void setUp() {
        h2 = new TestDb("converter_reg_" + DB_SEQ.incrementAndGet());
        LightQuery.reset();
        LightQuery.clearConverters();
        LightQuery.primary(h2.dataSource);
        try (Connection c = h2.dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE \"t_wallet\" ("
                    + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "\"owner\" VARCHAR(50), \"amount_cents\" BIGINT, \"bonus_cents\" BIGINT)");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private long rawAmount(String owner) throws Exception {
        try (Connection c = h2.dataSource.getConnection();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                     "SELECT \"amount_cents\" FROM \"t_wallet\" WHERE \"owner\" = '" + owner + "'")) {
            rs.next();
            return rs.getLong(1);
        }
    }

    @Test
    void globalConverterRoundTripsWriteReadAndConditionBinding() throws Exception {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.MoneyConverter());
        LightQuery.insert(new Wallet("alice", new Wallet.Money(1234L), new Wallet.Money(50L)));

        // write path: Money -> Long cents in the DB
        assertEquals(1234L, rawAmount("alice"));

        // read path: Long cents -> Money on the entity
        Wallet loaded = LightQuery.queryById(Wallet.class, LightQuery.queryable(Wallet.class)
                .col(Wallet::getOwner).eq("alice").firstOrNull().getId());
        assertEquals(new Wallet.Money(1234L), loaded.getAmount());

        // condition bind values convert too
        long n = LightQuery.queryable(Wallet.class)
                .col(Wallet::getAmount).eq(new Wallet.Money(1234L))
                .count();
        assertEquals(1, n);
    }

    @Test
    void fieldLevelConvertTakesPrecedenceOverGlobal() {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.MoneyConverter());
        LightQuery.insert(new Wallet("bob", new Wallet.Money(10L), new Wallet.Money(20L)));
        // bonus column stores the MARKING converter's value (+1e9), not the global one
        try (Connection c = h2.dataSource.getConnection();
             ResultSet rs = c.createStatement().executeQuery(
                     "SELECT \"bonus_cents\" FROM \"t_wallet\" WHERE \"owner\" = 'bob'")) {
            rs.next();
            assertEquals(1_000_000_020L, rs.getLong(1));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    void nullPassesThroughWithoutTouchingTheConverter() {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.ExplodingConverter());
        // Exploding would throw on any non-null value; null must skip it entirely
        Wallet w = LightQuery.insert(new Wallet("carol", null, null));
        assertNull(LightQuery.queryable(Wallet.class)
                .col(Wallet::getOwner).eq("carol").firstOrNull().getAmount());
        assertNull(w.getAmount());
    }

    @Test
    void duplicateRegistrationIsRejected() {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.MoneyConverter());
        var ex = assertThrows(IllegalStateException.class,
                () -> LightQuery.registerConverter(Wallet.Money.class, new Wallet.MoneyConverter()));
        org.junit.jupiter.api.Assertions.assertTrue(
                ex.getMessage().contains("already registered"), ex.getMessage());
    }

    @Test
    void matchingIsByExactTypeOnly() {
        // registered for the supertype — must NOT fire for the Money-typed column
        LightQuery.registerConverter(Number.class, new Wallet.MoneyConverter());
        // without conversion the insert cannot map Money -> BIGINT and fails
        assertThrows(Exception.class,
                () -> LightQuery.insert(new Wallet("dave", new Wallet.Money(1L), null)));
    }

    @Test
    void converterFailureIsWrappedWithColumnAndProperty() {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.ExplodingConverter());
        var ex = assertThrows(MappingException.class,
                () -> LightQuery.insert(new Wallet("erin", new Wallet.Money(1L), null)));
        org.junit.jupiter.api.Assertions.assertTrue(
                ex.getMessage().contains("amount_cents")
                        && ex.getMessage().contains("ExplodingConverter"),
                ex.getMessage());
        org.junit.jupiter.api.Assertions.assertEquals("boom",
                ex.getCause().getMessage());
    }

    @Test
    void clearConvertersRemovesTheMapping() {
        LightQuery.registerConverter(Wallet.Money.class, new Wallet.MoneyConverter());
        LightQuery.clearConverters();
        assertThrows(Exception.class,
                () -> LightQuery.insert(new Wallet("frank", new Wallet.Money(1L), null)));
    }
}
