package com.lightquery;

import com.lightquery.entity.User;
import com.lightquery.exception.MappingException;
import com.lightquery.support.TestDb;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Converter;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** T22 — JPA @Convert / AttributeConverter transparent support. */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ConverterH2Test {

    private TestDb h2;

    @Converter
    public static class UpperCaseConverter implements AttributeConverter<String, String> {
        public String convertToDatabaseColumn(String attribute) {
            return attribute == null ? null : attribute.toUpperCase();
        }
        public String convertToEntityAttribute(String dbData) {
            return dbData == null ? null : dbData.toLowerCase();
        }
    }

    @Entity
    @Table(name = "t_convert_doc")
    public static class ConvertedDoc {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;

        @Convert(converter = UpperCaseConverter.class)
        @Column(name = "title")
        private String title;

        public ConvertedDoc() {}
        public ConvertedDoc(String title) { this.title = title; }
        public Long getId() { return id; }
        public String getTitle() { return title; }
    }

    @Entity
    @Table(name = "t_convert_bad")
    public static class BadConvertedDoc {
        @Id
        @jakarta.persistence.GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;
        @Convert
        @Column(name = "title")
        private String title;
    }

    @BeforeAll
    void setUp() {
        h2 = new TestDb("converter");
        try (var c = h2.dataSource.getConnection(); var st = c.createStatement()) {
            st.execute("DROP TABLE IF EXISTS \"t_convert_doc\"");
            st.execute("CREATE TABLE \"t_convert_doc\" ("
                    + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "\"title\" VARCHAR(200))");
            st.execute("DROP TABLE IF EXISTS \"t_convert_bad\"");
        } catch (Exception e) {
            throw new IllegalStateException("schema", e);
        }
    }

    @Test
    void converterAppliesOnInsertAndSelect() {
        ConvertedDoc doc = LightQuery.insert(new ConvertedDoc("hello world"));
        Long id = doc.getId();
        assertTrue(id != null);
        // raw check: stored value is uppercase
        String raw = LightQuery.queryable(ConvertedDoc.class)
                .col(ConvertedDoc::getTitle).eq("HELLO WORLD")
                .toList().stream().findFirst().map(ConvertedDoc::getTitle).orElse(null);
        // read back: converter lowercases
        ConvertedDoc loaded = LightQuery.queryById(ConvertedDoc.class, id);
        assertEquals("hello world", loaded.getTitle());
    }

    @Test
    void converterAppliesOnCondition() {
        LightQuery.insert(new ConvertedDoc("find me"));
        // condition value "FIND ME" matches the DB (uppercased by converter)
        var rows = LightQuery.queryable(ConvertedDoc.class)
                .col(ConvertedDoc::getTitle).eq("FIND ME")
                .toList();
        assertEquals(1, rows.size());
    }

    @Test
    void converterWithoutClassIsRejected() {
        MappingException e = assertThrows(MappingException.class,
                () -> LightQuery.queryable(BadConvertedDoc.class).toList());
        assertTrue(e.getMessage().contains("converter"), e.getMessage());
    }
}
