package com.lightquery;

import com.lightquery.exception.MappingException;
import com.lightquery.meta.ColumnMeta;
import com.lightquery.meta.EntityMeta;
import com.lightquery.meta.EntityMetaCache;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** T1 — entity metadata: naming, annotations, constructor-time validation. */
class EntityMetaTest {

    @Test
    void camelToSnakeConvertsNames() {
        assertEquals("user_name", EntityMeta.camelToSnake("userName"));
        assertEquals("created_at", EntityMeta.camelToSnake("createdAt"));
        assertEquals("url", EntityMeta.camelToSnake("URL"));
        assertEquals("xml_http_request", EntityMeta.camelToSnake("xmlHttpRequest"));
    }

    @Test
    void readsTableColumnAndFlags() {
        EntityMeta meta = EntityMetaCache.of(WellMapped.class);

        assertEquals("t_well_mapped", meta.getTableName());
        assertEquals(WellMapped.class, meta.getEntityClass());

        ColumnMeta id = meta.byProperty("id");
        assertTrue(id.isPrimaryKey());
        assertTrue(id.isAutoGenerated());

        assertEquals("login_name", meta.byProperty("loginName").getColumnName());
        assertTrue(meta.byProperty("loginName").isUpdatable());
        assertTrue(!meta.byProperty("readOnly").isInsertable());
        assertTrue(!meta.byProperty("readOnly").isUpdatable());
    }

    @Test
    void findsColumnsByResultSetLabel() {
        EntityMeta meta = EntityMetaCache.of(WellMapped.class);
        assertEquals("login_name", meta.byLabel("login_name").getColumnName());
        assertEquals("login_name", meta.byLabel("LOGIN_NAME").getColumnName());
        assertTrue(meta.byLabel("camelCased") == null);
        assertEquals(null, meta.byLabel("not_a_column"));
    }

    @Test
    void rejectsEntityWithoutPrimaryKey() {
        MappingException e = assertThrows(MappingException.class,
                () -> EntityMetaCache.of(NoKey.class));
        assertTrue(e.getMessage().contains("@Id"));
    }

    @Test
    void rejectsDuplicateColumnMapping() {
        MappingException e = assertThrows(MappingException.class,
                () -> EntityMetaCache.of(DuplicateColumn.class));
        assertTrue(e.getMessage().contains("same column"));
    }

    // ------------------------------------------------------------------ fixtures

    @Entity
    @Table(name = "t_well_mapped")
    static class WellMapped {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        Long id;

        @Column(name = "login_name")
        String loginName;

        @Column(name = "read_only", insertable = false, updatable = false)
        String readOnly;
    }

    @Entity
    static class NoKey {
        String name;
    }

    @Entity
    static class DuplicateColumn {
        @Id
        Long id;

        @Column(name = "same")
        String one;

        @Column(name = "same")
        String two;
    }
}
