package com.lightquery;

import com.lightquery.entity.VersionedArticle;
import com.lightquery.entity.VersionedDoc;
import com.lightquery.exception.MappingException;
import com.lightquery.meta.EntityMetaCache;

import org.h2.jdbcx.JdbcDataSource;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OptimisticLockException;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import java.sql.Connection;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** T12 — @Version optimistic locking on entity-level writes. */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OptimisticLockH2Test {

    private JdbcDataSource dataSource;

    @BeforeAll
    void setUp() {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:optlock;DB_CLOSE_DELAY=-1");
        LightQuery.reset();
        LightQuery.primary(dataSource);
        try (Connection connection = dataSource.getConnection();
             Statement st = connection.createStatement()) {
            st.execute("DROP TABLE IF EXISTS \"t_versioned_doc\"");
            st.execute("""
                    CREATE TABLE "t_versioned_doc" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "title" VARCHAR(200),
                        "version" INT DEFAULT 0
                    )""");
            st.execute("DROP TABLE IF EXISTS \"t_versioned_article\"");
            st.execute("""
                    CREATE TABLE "t_versioned_article" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "title" VARCHAR(200),
                        "version" INT DEFAULT 0,
                        "deleted" INT DEFAULT 0
                    )""");
        } catch (Exception e) {
            throw new IllegalStateException("cannot prepare H2 schema", e);
        }
    }

    @Test
    void insertInitialisesVersionToZero() {
        VersionedDoc doc = LightQuery.insert(new VersionedDoc("insert-version"));
        assertEquals(0, doc.getVersion());
        assertEquals(0, LightQuery.queryById(VersionedDoc.class, doc.getId()).getVersion());
    }

    @Test
    void updateBumpsVersionAndBackfills() {
        VersionedDoc doc = LightQuery.insert(new VersionedDoc("update-version"));
        doc.setTitle("update-version-2");
        LightQuery.update(doc);
        assertEquals(1, doc.getVersion());
        VersionedDoc loaded = LightQuery.queryById(VersionedDoc.class, doc.getId());
        assertEquals(1, loaded.getVersion());
        assertEquals("update-version-2", loaded.getTitle());
    }

    @Test
    void updateSelectiveAlsoAppliesVersion() {
        VersionedDoc doc = LightQuery.insert(new VersionedDoc("selective-version"));
        doc.setTitle("selective-version-2");
        LightQuery.updateSelective(doc);
        assertEquals(1, doc.getVersion());
        assertEquals(1, LightQuery.queryById(VersionedDoc.class, doc.getId()).getVersion());
    }

    @Test
    void staleVersionFailsWithOptimisticLockException() {
        VersionedDoc doc = LightQuery.insert(new VersionedDoc("conflict"));
        VersionedDoc firstReader = LightQuery.queryById(VersionedDoc.class, doc.getId());
        VersionedDoc secondReader = LightQuery.queryById(VersionedDoc.class, doc.getId());

        firstReader.setTitle("winner");
        LightQuery.update(firstReader);

        secondReader.setTitle("loser");
        OptimisticLockException e = assertThrows(OptimisticLockException.class,
                () -> LightQuery.update(secondReader));
        assertTrue(e.getMessage().contains("concurrently"), e.getMessage());
        // the losing update wrote nothing
        assertEquals("winner", LightQuery.queryById(VersionedDoc.class, doc.getId()).getTitle());
    }

    @Test
    void deleteUsesVersionPredicate() {
        VersionedDoc doc = LightQuery.insert(new VersionedDoc("delete-version"));
        LightQuery.delete(doc);
        assertEquals(null, LightQuery.queryById(VersionedDoc.class, doc.getId()));
        // replaying the delete with the stale entity affects 0 rows → optimistic lock failure
        assertThrows(OptimisticLockException.class, () -> LightQuery.delete(doc));
    }

    @Test
    void logicDeleteBumpsVersion() {
        VersionedArticle article = LightQuery.insert(new VersionedArticle("article"));
        LightQuery.delete(article);
        assertEquals(1, article.getVersion());
        VersionedArticle loaded = LightQuery.queryById(VersionedArticle.class, article.getId());
        assertEquals(null, loaded);
    }

    @Test
    void versionTypeIsRestricted() {
        MappingException e = assertThrows(MappingException.class,
                () -> EntityMetaCache.of(StringVersioned.class));
        assertTrue(e.getMessage().contains("int/Integer/long/Long"), e.getMessage());
    }

    @Test
    void multipleVersionFieldsFail() {
        MappingException e = assertThrows(MappingException.class,
                () -> EntityMetaCache.of(TwiceVersioned.class));
        assertTrue(e.getMessage().contains("more than one @Version"), e.getMessage());
    }

    @Table(name = "t_missing")
    static class StringVersioned {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        Long id;
        @Version
        String version;
    }

    @Table(name = "t_missing")
    static class TwiceVersioned {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        Long id;
        @Version
        Integer version;
        @Version
        Long revision;
    }
}
